create table redis.redis_client (
  target_id int,
  collection_time timestamp,
  id int8,
  addr varchar(255),
  local_addr varchar(255),
  fd int8,
  name varchar(255),
  age int8,
  idle int8,
  flags varchar(255),
  db int8,
  sub int8,
  psub int8,
  ssub int8,
  multi int8,
  qbuf text,
  qbuf_free int8,
  argv_mem int8,
  multi_mem int8,
  rbs int8,
  rbp int8,
  obl int8,
  oll int8,
  omem int8,
  tot_mem int8,
  events varchar(255),
  cmd varchar(255),
  user varchar(255),
  redir int8,
  resp int8,
  lib_name varchar(255),
  lib_ver varchar(255)
) partition by range(collection_time);

create index redis_client_idx on redis.redis_client(target_id, collection_time, id);
