// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `sockstat.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_3_0;

// @@protoc_insertion_point(message:net.SockStatInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SockStatInfo {
    // message fields
    // @@protoc_insertion_point(field:net.SockStatInfo.use_count)
    pub use_count: u64,
    // @@protoc_insertion_point(field:net.SockStatInfo.in_use)
    pub in_use: u64,
    // @@protoc_insertion_point(field:net.SockStatInfo.orphan)
    pub orphan: u64,
    // @@protoc_insertion_point(field:net.SockStatInfo.tw)
    pub tw: u64,
    // @@protoc_insertion_point(field:net.SockStatInfo.alloc)
    pub alloc: u64,
    // @@protoc_insertion_point(field:net.SockStatInfo.mem_kb)
    pub mem_kb: f64,
    // special fields
    // @@protoc_insertion_point(special_field:net.SockStatInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SockStatInfo {
    fn default() -> &'a SockStatInfo {
        <SockStatInfo as ::protobuf::Message>::default_instance()
    }
}

impl SockStatInfo {
    pub fn new() -> SockStatInfo {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "use_count",
            |m: &SockStatInfo| { &m.use_count },
            |m: &mut SockStatInfo| { &mut m.use_count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "in_use",
            |m: &SockStatInfo| { &m.in_use },
            |m: &mut SockStatInfo| { &mut m.in_use },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "orphan",
            |m: &SockStatInfo| { &m.orphan },
            |m: &mut SockStatInfo| { &mut m.orphan },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tw",
            |m: &SockStatInfo| { &m.tw },
            |m: &mut SockStatInfo| { &mut m.tw },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "alloc",
            |m: &SockStatInfo| { &m.alloc },
            |m: &mut SockStatInfo| { &mut m.alloc },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "mem_kb",
            |m: &SockStatInfo| { &m.mem_kb },
            |m: &mut SockStatInfo| { &mut m.mem_kb },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SockStatInfo>(
            "SockStatInfo",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SockStatInfo {
    const NAME: &'static str = "SockStatInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.use_count = is.read_uint64()?;
                },
                16 => {
                    self.in_use = is.read_uint64()?;
                },
                24 => {
                    self.orphan = is.read_uint64()?;
                },
                32 => {
                    self.tw = is.read_uint64()?;
                },
                40 => {
                    self.alloc = is.read_uint64()?;
                },
                49 => {
                    self.mem_kb = is.read_double()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.use_count != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.use_count);
        }
        if self.in_use != 0 {
            my_size += ::protobuf::rt::uint64_size(2, self.in_use);
        }
        if self.orphan != 0 {
            my_size += ::protobuf::rt::uint64_size(3, self.orphan);
        }
        if self.tw != 0 {
            my_size += ::protobuf::rt::uint64_size(4, self.tw);
        }
        if self.alloc != 0 {
            my_size += ::protobuf::rt::uint64_size(5, self.alloc);
        }
        if self.mem_kb != 0. {
            my_size += 1 + 8;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.use_count != 0 {
            os.write_uint64(1, self.use_count)?;
        }
        if self.in_use != 0 {
            os.write_uint64(2, self.in_use)?;
        }
        if self.orphan != 0 {
            os.write_uint64(3, self.orphan)?;
        }
        if self.tw != 0 {
            os.write_uint64(4, self.tw)?;
        }
        if self.alloc != 0 {
            os.write_uint64(5, self.alloc)?;
        }
        if self.mem_kb != 0. {
            os.write_double(6, self.mem_kb)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SockStatInfo {
        SockStatInfo::new()
    }

    fn clear(&mut self) {
        self.use_count = 0;
        self.in_use = 0;
        self.orphan = 0;
        self.tw = 0;
        self.alloc = 0;
        self.mem_kb = 0.;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SockStatInfo {
        static instance: SockStatInfo = SockStatInfo {
            use_count: 0,
            in_use: 0,
            orphan: 0,
            tw: 0,
            alloc: 0,
            mem_kb: 0.,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SockStatInfo {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SockStatInfo").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SockStatInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SockStatInfo {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0esockstat.proto\x12\x03net\"\x97\x01\n\x0cSockStatInfo\x12\x1b\n\tu\
    se_count\x18\x01\x20\x01(\x04R\x08useCount\x12\x15\n\x06in_use\x18\x02\
    \x20\x01(\x04R\x05inUse\x12\x16\n\x06orphan\x18\x03\x20\x01(\x04R\x06orp\
    han\x12\x0e\n\x02tw\x18\x04\x20\x01(\x04R\x02tw\x12\x14\n\x05alloc\x18\
    \x05\x20\x01(\x04R\x05alloc\x12\x15\n\x06mem_kb\x18\x06\x20\x01(\x01R\
    \x05memKbb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(SockStatInfo::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
