// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: db_size.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DbSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size      int64  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	UnixEpoch uint64 `protobuf:"varint,2,opt,name=unix_epoch,json=unixEpoch,proto3" json:"unix_epoch,omitempty"`
}

func (x *DbSize) Reset() {
	*x = DbSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_size_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbSize) ProtoMessage() {}

func (x *DbSize) ProtoReflect() protoreflect.Message {
	mi := &file_db_size_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbSize.ProtoReflect.Descriptor instead.
func (*DbSize) Descriptor() ([]byte, []int) {
	return file_db_size_proto_rawDescGZIP(), []int{0}
}

func (x *DbSize) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DbSize) GetUnixEpoch() uint64 {
	if x != nil {
		return x.UnixEpoch
	}
	return 0
}

var File_db_size_proto protoreflect.FileDescriptor

var file_db_size_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x62, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x2e, 0x72, 0x65, 0x64, 0x69, 0x73, 0x22, 0x3b, 0x0a, 0x06,
	0x44, 0x62, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x6e,
	0x69, 0x78, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x75, 0x6e, 0x69, 0x78, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x42, 0x30, 0x5a, 0x08, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0xaa, 0x02, 0x23, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x48, 0x75, 0x62, 0x2e, 0x48, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_db_size_proto_rawDescOnce sync.Once
	file_db_size_proto_rawDescData = file_db_size_proto_rawDesc
)

func file_db_size_proto_rawDescGZIP() []byte {
	file_db_size_proto_rawDescOnce.Do(func() {
		file_db_size_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_size_proto_rawDescData)
	})
	return file_db_size_proto_rawDescData
}

var file_db_size_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_db_size_proto_goTypes = []interface{}{
	(*DbSize)(nil), // 0: agnet.redis.DbSize
}
var file_db_size_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_size_proto_init() }
func file_db_size_proto_init() {
	if File_db_size_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_db_size_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_size_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_size_proto_goTypes,
		DependencyIndexes: file_db_size_proto_depIdxs,
		MessageInfos:      file_db_size_proto_msgTypes,
	}.Build()
	File_db_size_proto = out.File
	file_db_size_proto_rawDesc = nil
	file_db_size_proto_goTypes = nil
	file_db_size_proto_depIdxs = nil
}
