// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: redis_snap.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataFormat int32

const (
	DataFormat_InfoMemory  DataFormat = 0
	DataFormat_InfoCPU     DataFormat = 1
	DataFormat_InfoStat    DataFormat = 2
	DataFormat_DBSize      DataFormat = 3
	DataFormat_ClientLists DataFormat = 4
)

// Enum value maps for DataFormat.
var (
	DataFormat_name = map[int32]string{
		0: "InfoMemory",
		1: "InfoCPU",
		2: "InfoStat",
		3: "DBSize",
		4: "ClientLists",
	}
	DataFormat_value = map[string]int32{
		"InfoMemory":  0,
		"InfoCPU":     1,
		"InfoStat":    2,
		"DBSize":      3,
		"ClientLists": 4,
	}
)

func (x DataFormat) Enum() *DataFormat {
	p := new(DataFormat)
	*p = x
	return p
}

func (x DataFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_redis_snap_proto_enumTypes[0].Descriptor()
}

func (DataFormat) Type() protoreflect.EnumType {
	return &file_redis_snap_proto_enumTypes[0]
}

func (x DataFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataFormat.Descriptor instead.
func (DataFormat) EnumDescriptor() ([]byte, []int) {
	return file_redis_snap_proto_rawDescGZIP(), []int{0}
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Format  DataFormat `protobuf:"varint,1,opt,name=format,proto3,enum=agent.redis.DataFormat" json:"format,omitempty"`
	RawData []byte     `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_snap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_redis_snap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_redis_snap_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetFormat() DataFormat {
	if x != nil {
		return x.Format
	}
	return DataFormat_InfoMemory
}

func (x *Data) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type AgentRedisSnap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnixEpoch uint64  `protobuf:"varint,1,opt,name=unix_epoch,json=unixEpoch,proto3" json:"unix_epoch,omitempty"`
	Datas     []*Data `protobuf:"bytes,2,rep,name=datas,proto3" json:"datas,omitempty"`
}

func (x *AgentRedisSnap) Reset() {
	*x = AgentRedisSnap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_snap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentRedisSnap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRedisSnap) ProtoMessage() {}

func (x *AgentRedisSnap) ProtoReflect() protoreflect.Message {
	mi := &file_redis_snap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRedisSnap.ProtoReflect.Descriptor instead.
func (*AgentRedisSnap) Descriptor() ([]byte, []int) {
	return file_redis_snap_proto_rawDescGZIP(), []int{1}
}

func (x *AgentRedisSnap) GetUnixEpoch() uint64 {
	if x != nil {
		return x.UnixEpoch
	}
	return 0
}

func (x *AgentRedisSnap) GetDatas() []*Data {
	if x != nil {
		return x.Datas
	}
	return nil
}

var File_redis_snap_proto protoreflect.FileDescriptor

var file_redis_snap_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x72, 0x65, 0x64, 0x69, 0x73, 0x22,
	0x52, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x72, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x61, 0x77, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x58, 0x0a, 0x0e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x64, 0x69,
	0x73, 0x53, 0x6e, 0x61, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x65, 0x70,
	0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x78, 0x45,
	0x70, 0x6f, 0x63, 0x68, 0x12, 0x27, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x72, 0x65, 0x64, 0x69,
	0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x2a, 0x54, 0x0a,
	0x0a, 0x44, 0x61, 0x74, 0x61, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x0a, 0x49,
	0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x6e, 0x66, 0x6f, 0x43, 0x50, 0x55, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x6e, 0x66, 0x6f,
	0x53, 0x74, 0x61, 0x74, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x42, 0x53, 0x69, 0x7a, 0x65,
	0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x73, 0x10, 0x04, 0x42, 0x30, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0xaa,
	0x02, 0x23, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x48, 0x75, 0x62, 0x2e,
	0x48, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x52, 0x65, 0x64, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_redis_snap_proto_rawDescOnce sync.Once
	file_redis_snap_proto_rawDescData = file_redis_snap_proto_rawDesc
)

func file_redis_snap_proto_rawDescGZIP() []byte {
	file_redis_snap_proto_rawDescOnce.Do(func() {
		file_redis_snap_proto_rawDescData = protoimpl.X.CompressGZIP(file_redis_snap_proto_rawDescData)
	})
	return file_redis_snap_proto_rawDescData
}

var file_redis_snap_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_redis_snap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_redis_snap_proto_goTypes = []interface{}{
	(DataFormat)(0),        // 0: agent.redis.DataFormat
	(*Data)(nil),           // 1: agent.redis.Data
	(*AgentRedisSnap)(nil), // 2: agent.redis.AgentRedisSnap
}
var file_redis_snap_proto_depIdxs = []int32{
	0, // 0: agent.redis.Data.format:type_name -> agent.redis.DataFormat
	1, // 1: agent.redis.AgentRedisSnap.datas:type_name -> agent.redis.Data
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_redis_snap_proto_init() }
func file_redis_snap_proto_init() {
	if File_redis_snap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_redis_snap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_snap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentRedisSnap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redis_snap_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_redis_snap_proto_goTypes,
		DependencyIndexes: file_redis_snap_proto_depIdxs,
		EnumInfos:         file_redis_snap_proto_enumTypes,
		MessageInfos:      file_redis_snap_proto_msgTypes,
	}.Build()
	File_redis_snap_proto = out.File
	file_redis_snap_proto_rawDesc = nil
	file_redis_snap_proto_goTypes = nil
	file_redis_snap_proto_depIdxs = nil
}
