// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: snap.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapFormat int32

const (
	SnapFormat_Os    SnapFormat = 0
	SnapFormat_Redis SnapFormat = 1
)

// Enum value maps for SnapFormat.
var (
	SnapFormat_name = map[int32]string{
		0: "Os",
		1: "Redis",
	}
	SnapFormat_value = map[string]int32{
		"Os":    0,
		"Redis": 1,
	}
)

func (x SnapFormat) Enum() *SnapFormat {
	p := new(SnapFormat)
	*p = x
	return p
}

func (x SnapFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_snap_proto_enumTypes[0].Descriptor()
}

func (SnapFormat) Type() protoreflect.EnumType {
	return &file_snap_proto_enumTypes[0]
}

func (x SnapFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapFormat.Descriptor instead.
func (SnapFormat) EnumDescriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{0}
}

type SnapData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Format  SnapFormat `protobuf:"varint,1,opt,name=format,proto3,enum=agent.SnapFormat" json:"format,omitempty"`
	RawSnap []byte     `protobuf:"bytes,2,opt,name=raw_snap,json=rawSnap,proto3" json:"raw_snap,omitempty"`
}

func (x *SnapData) Reset() {
	*x = SnapData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapData) ProtoMessage() {}

func (x *SnapData) ProtoReflect() protoreflect.Message {
	mi := &file_snap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapData.ProtoReflect.Descriptor instead.
func (*SnapData) Descriptor() ([]byte, []int) {
	return file_snap_proto_rawDescGZIP(), []int{0}
}

func (x *SnapData) GetFormat() SnapFormat {
	if x != nil {
		return x.Format
	}
	return SnapFormat_Os
}

func (x *SnapData) GetRawSnap() []byte {
	if x != nil {
		return x.RawSnap
	}
	return nil
}

var File_snap_proto protoreflect.FileDescriptor

var file_snap_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x22, 0x50, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x29, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61,
	0x77, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x61,
	0x77, 0x53, 0x6e, 0x61, 0x70, 0x2a, 0x1f, 0x0a, 0x0a, 0x53, 0x6e, 0x61, 0x70, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x73, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52,
	0x65, 0x64, 0x69, 0x73, 0x10, 0x01, 0x42, 0x2a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0xaa, 0x02, 0x1d, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x48,
	0x75, 0x62, 0x2e, 0x48, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snap_proto_rawDescOnce sync.Once
	file_snap_proto_rawDescData = file_snap_proto_rawDesc
)

func file_snap_proto_rawDescGZIP() []byte {
	file_snap_proto_rawDescOnce.Do(func() {
		file_snap_proto_rawDescData = protoimpl.X.CompressGZIP(file_snap_proto_rawDescData)
	})
	return file_snap_proto_rawDescData
}

var file_snap_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_snap_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_snap_proto_goTypes = []interface{}{
	(SnapFormat)(0),  // 0: agent.SnapFormat
	(*SnapData)(nil), // 1: agent.SnapData
}
var file_snap_proto_depIdxs = []int32{
	0, // 0: agent.SnapData.format:type_name -> agent.SnapFormat
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_snap_proto_init() }
func file_snap_proto_init() {
	if File_snap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snap_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snap_proto_goTypes,
		DependencyIndexes: file_snap_proto_depIdxs,
		EnumInfos:         file_snap_proto_enumTypes,
		MessageInfos:      file_snap_proto_msgTypes,
	}.Build()
	File_snap_proto = out.File
	file_snap_proto_rawDesc = nil
	file_snap_proto_goTypes = nil
	file_snap_proto_depIdxs = nil
}
