// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `net.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_3_0;

// @@protoc_insertion_point(message:agent.os.net.ArpInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ArpInfo {
    // message fields
    // @@protoc_insertion_point(field:agent.os.net.ArpInfo.ip_address)
    pub ip_address: ::std::string::String,
    // @@protoc_insertion_point(field:agent.os.net.ArpInfo.hw_type)
    pub hw_type: u32,
    // @@protoc_insertion_point(field:agent.os.net.ArpInfo.flags)
    pub flags: ::std::string::String,
    // @@protoc_insertion_point(field:agent.os.net.ArpInfo.device)
    pub device: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:agent.os.net.ArpInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ArpInfo {
    fn default() -> &'a ArpInfo {
        <ArpInfo as ::protobuf::Message>::default_instance()
    }
}

impl ArpInfo {
    pub fn new() -> ArpInfo {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ip_address",
            |m: &ArpInfo| { &m.ip_address },
            |m: &mut ArpInfo| { &mut m.ip_address },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "hw_type",
            |m: &ArpInfo| { &m.hw_type },
            |m: &mut ArpInfo| { &mut m.hw_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "flags",
            |m: &ArpInfo| { &m.flags },
            |m: &mut ArpInfo| { &mut m.flags },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "device",
            |m: &ArpInfo| { &m.device },
            |m: &mut ArpInfo| { &mut m.device },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ArpInfo>(
            "ArpInfo",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ArpInfo {
    const NAME: &'static str = "ArpInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.ip_address = is.read_string()?;
                },
                16 => {
                    self.hw_type = is.read_uint32()?;
                },
                26 => {
                    self.flags = is.read_string()?;
                },
                34 => {
                    self.device = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.ip_address.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.ip_address);
        }
        if self.hw_type != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.hw_type);
        }
        if !self.flags.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.flags);
        }
        if !self.device.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.device);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.ip_address.is_empty() {
            os.write_string(1, &self.ip_address)?;
        }
        if self.hw_type != 0 {
            os.write_uint32(2, self.hw_type)?;
        }
        if !self.flags.is_empty() {
            os.write_string(3, &self.flags)?;
        }
        if !self.device.is_empty() {
            os.write_string(4, &self.device)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ArpInfo {
        ArpInfo::new()
    }

    fn clear(&mut self) {
        self.ip_address.clear();
        self.hw_type = 0;
        self.flags.clear();
        self.device.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ArpInfo {
        static instance: ArpInfo = ArpInfo {
            ip_address: ::std::string::String::new(),
            hw_type: 0,
            flags: ::std::string::String::new(),
            device: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ArpInfo {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ArpInfo").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ArpInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ArpInfo {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:agent.os.net.ArpInfos)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ArpInfos {
    // message fields
    // @@protoc_insertion_point(field:agent.os.net.ArpInfos.infos)
    pub infos: ::std::vec::Vec<ArpInfo>,
    // special fields
    // @@protoc_insertion_point(special_field:agent.os.net.ArpInfos.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ArpInfos {
    fn default() -> &'a ArpInfos {
        <ArpInfos as ::protobuf::Message>::default_instance()
    }
}

impl ArpInfos {
    pub fn new() -> ArpInfos {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "infos",
            |m: &ArpInfos| { &m.infos },
            |m: &mut ArpInfos| { &mut m.infos },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ArpInfos>(
            "ArpInfos",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ArpInfos {
    const NAME: &'static str = "ArpInfos";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.infos.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.infos {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.infos {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ArpInfos {
        ArpInfos::new()
    }

    fn clear(&mut self) {
        self.infos.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ArpInfos {
        static instance: ArpInfos = ArpInfos {
            infos: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ArpInfos {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ArpInfos").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ArpInfos {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ArpInfos {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:agent.os.net.NetDevInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct NetDevInfo {
    // message fields
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.interface)
    pub interface: ::std::string::String,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.rx_bytes)
    pub rx_bytes: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.rx_packets)
    pub rx_packets: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.rx_errs)
    pub rx_errs: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.rx_drop)
    pub rx_drop: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.rx_fifo)
    pub rx_fifo: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.rx_frame)
    pub rx_frame: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.rx_compressed)
    pub rx_compressed: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.tx_bytes)
    pub tx_bytes: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.tx_packets)
    pub tx_packets: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.tx_errs)
    pub tx_errs: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.tx_drop)
    pub tx_drop: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.tx_fifo)
    pub tx_fifo: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.tx_frame)
    pub tx_frame: u64,
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfo.tx_compressed)
    pub tx_compressed: u64,
    // special fields
    // @@protoc_insertion_point(special_field:agent.os.net.NetDevInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NetDevInfo {
    fn default() -> &'a NetDevInfo {
        <NetDevInfo as ::protobuf::Message>::default_instance()
    }
}

impl NetDevInfo {
    pub fn new() -> NetDevInfo {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(15);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "interface",
            |m: &NetDevInfo| { &m.interface },
            |m: &mut NetDevInfo| { &mut m.interface },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "rx_bytes",
            |m: &NetDevInfo| { &m.rx_bytes },
            |m: &mut NetDevInfo| { &mut m.rx_bytes },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "rx_packets",
            |m: &NetDevInfo| { &m.rx_packets },
            |m: &mut NetDevInfo| { &mut m.rx_packets },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "rx_errs",
            |m: &NetDevInfo| { &m.rx_errs },
            |m: &mut NetDevInfo| { &mut m.rx_errs },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "rx_drop",
            |m: &NetDevInfo| { &m.rx_drop },
            |m: &mut NetDevInfo| { &mut m.rx_drop },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "rx_fifo",
            |m: &NetDevInfo| { &m.rx_fifo },
            |m: &mut NetDevInfo| { &mut m.rx_fifo },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "rx_frame",
            |m: &NetDevInfo| { &m.rx_frame },
            |m: &mut NetDevInfo| { &mut m.rx_frame },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "rx_compressed",
            |m: &NetDevInfo| { &m.rx_compressed },
            |m: &mut NetDevInfo| { &mut m.rx_compressed },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tx_bytes",
            |m: &NetDevInfo| { &m.tx_bytes },
            |m: &mut NetDevInfo| { &mut m.tx_bytes },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tx_packets",
            |m: &NetDevInfo| { &m.tx_packets },
            |m: &mut NetDevInfo| { &mut m.tx_packets },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tx_errs",
            |m: &NetDevInfo| { &m.tx_errs },
            |m: &mut NetDevInfo| { &mut m.tx_errs },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tx_drop",
            |m: &NetDevInfo| { &m.tx_drop },
            |m: &mut NetDevInfo| { &mut m.tx_drop },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tx_fifo",
            |m: &NetDevInfo| { &m.tx_fifo },
            |m: &mut NetDevInfo| { &mut m.tx_fifo },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tx_frame",
            |m: &NetDevInfo| { &m.tx_frame },
            |m: &mut NetDevInfo| { &mut m.tx_frame },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tx_compressed",
            |m: &NetDevInfo| { &m.tx_compressed },
            |m: &mut NetDevInfo| { &mut m.tx_compressed },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NetDevInfo>(
            "NetDevInfo",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NetDevInfo {
    const NAME: &'static str = "NetDevInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.interface = is.read_string()?;
                },
                16 => {
                    self.rx_bytes = is.read_uint64()?;
                },
                24 => {
                    self.rx_packets = is.read_uint64()?;
                },
                32 => {
                    self.rx_errs = is.read_uint64()?;
                },
                40 => {
                    self.rx_drop = is.read_uint64()?;
                },
                48 => {
                    self.rx_fifo = is.read_uint64()?;
                },
                56 => {
                    self.rx_frame = is.read_uint64()?;
                },
                64 => {
                    self.rx_compressed = is.read_uint64()?;
                },
                72 => {
                    self.tx_bytes = is.read_uint64()?;
                },
                80 => {
                    self.tx_packets = is.read_uint64()?;
                },
                88 => {
                    self.tx_errs = is.read_uint64()?;
                },
                96 => {
                    self.tx_drop = is.read_uint64()?;
                },
                104 => {
                    self.tx_fifo = is.read_uint64()?;
                },
                112 => {
                    self.tx_frame = is.read_uint64()?;
                },
                120 => {
                    self.tx_compressed = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.interface.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.interface);
        }
        if self.rx_bytes != 0 {
            my_size += ::protobuf::rt::uint64_size(2, self.rx_bytes);
        }
        if self.rx_packets != 0 {
            my_size += ::protobuf::rt::uint64_size(3, self.rx_packets);
        }
        if self.rx_errs != 0 {
            my_size += ::protobuf::rt::uint64_size(4, self.rx_errs);
        }
        if self.rx_drop != 0 {
            my_size += ::protobuf::rt::uint64_size(5, self.rx_drop);
        }
        if self.rx_fifo != 0 {
            my_size += ::protobuf::rt::uint64_size(6, self.rx_fifo);
        }
        if self.rx_frame != 0 {
            my_size += ::protobuf::rt::uint64_size(7, self.rx_frame);
        }
        if self.rx_compressed != 0 {
            my_size += ::protobuf::rt::uint64_size(8, self.rx_compressed);
        }
        if self.tx_bytes != 0 {
            my_size += ::protobuf::rt::uint64_size(9, self.tx_bytes);
        }
        if self.tx_packets != 0 {
            my_size += ::protobuf::rt::uint64_size(10, self.tx_packets);
        }
        if self.tx_errs != 0 {
            my_size += ::protobuf::rt::uint64_size(11, self.tx_errs);
        }
        if self.tx_drop != 0 {
            my_size += ::protobuf::rt::uint64_size(12, self.tx_drop);
        }
        if self.tx_fifo != 0 {
            my_size += ::protobuf::rt::uint64_size(13, self.tx_fifo);
        }
        if self.tx_frame != 0 {
            my_size += ::protobuf::rt::uint64_size(14, self.tx_frame);
        }
        if self.tx_compressed != 0 {
            my_size += ::protobuf::rt::uint64_size(15, self.tx_compressed);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.interface.is_empty() {
            os.write_string(1, &self.interface)?;
        }
        if self.rx_bytes != 0 {
            os.write_uint64(2, self.rx_bytes)?;
        }
        if self.rx_packets != 0 {
            os.write_uint64(3, self.rx_packets)?;
        }
        if self.rx_errs != 0 {
            os.write_uint64(4, self.rx_errs)?;
        }
        if self.rx_drop != 0 {
            os.write_uint64(5, self.rx_drop)?;
        }
        if self.rx_fifo != 0 {
            os.write_uint64(6, self.rx_fifo)?;
        }
        if self.rx_frame != 0 {
            os.write_uint64(7, self.rx_frame)?;
        }
        if self.rx_compressed != 0 {
            os.write_uint64(8, self.rx_compressed)?;
        }
        if self.tx_bytes != 0 {
            os.write_uint64(9, self.tx_bytes)?;
        }
        if self.tx_packets != 0 {
            os.write_uint64(10, self.tx_packets)?;
        }
        if self.tx_errs != 0 {
            os.write_uint64(11, self.tx_errs)?;
        }
        if self.tx_drop != 0 {
            os.write_uint64(12, self.tx_drop)?;
        }
        if self.tx_fifo != 0 {
            os.write_uint64(13, self.tx_fifo)?;
        }
        if self.tx_frame != 0 {
            os.write_uint64(14, self.tx_frame)?;
        }
        if self.tx_compressed != 0 {
            os.write_uint64(15, self.tx_compressed)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NetDevInfo {
        NetDevInfo::new()
    }

    fn clear(&mut self) {
        self.interface.clear();
        self.rx_bytes = 0;
        self.rx_packets = 0;
        self.rx_errs = 0;
        self.rx_drop = 0;
        self.rx_fifo = 0;
        self.rx_frame = 0;
        self.rx_compressed = 0;
        self.tx_bytes = 0;
        self.tx_packets = 0;
        self.tx_errs = 0;
        self.tx_drop = 0;
        self.tx_fifo = 0;
        self.tx_frame = 0;
        self.tx_compressed = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NetDevInfo {
        static instance: NetDevInfo = NetDevInfo {
            interface: ::std::string::String::new(),
            rx_bytes: 0,
            rx_packets: 0,
            rx_errs: 0,
            rx_drop: 0,
            rx_fifo: 0,
            rx_frame: 0,
            rx_compressed: 0,
            tx_bytes: 0,
            tx_packets: 0,
            tx_errs: 0,
            tx_drop: 0,
            tx_fifo: 0,
            tx_frame: 0,
            tx_compressed: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NetDevInfo {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NetDevInfo").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NetDevInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NetDevInfo {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:agent.os.net.NetDevInfos)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct NetDevInfos {
    // message fields
    // @@protoc_insertion_point(field:agent.os.net.NetDevInfos.infos)
    pub infos: ::std::vec::Vec<NetDevInfo>,
    // special fields
    // @@protoc_insertion_point(special_field:agent.os.net.NetDevInfos.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NetDevInfos {
    fn default() -> &'a NetDevInfos {
        <NetDevInfos as ::protobuf::Message>::default_instance()
    }
}

impl NetDevInfos {
    pub fn new() -> NetDevInfos {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "infos",
            |m: &NetDevInfos| { &m.infos },
            |m: &mut NetDevInfos| { &mut m.infos },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NetDevInfos>(
            "NetDevInfos",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NetDevInfos {
    const NAME: &'static str = "NetDevInfos";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.infos.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.infos {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.infos {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NetDevInfos {
        NetDevInfos::new()
    }

    fn clear(&mut self) {
        self.infos.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NetDevInfos {
        static instance: NetDevInfos = NetDevInfos {
            infos: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NetDevInfos {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NetDevInfos").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NetDevInfos {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NetDevInfos {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:agent.os.net.SockStatInfo)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SockStatInfo {
    // message fields
    // @@protoc_insertion_point(field:agent.os.net.SockStatInfo.use_count)
    pub use_count: u64,
    // @@protoc_insertion_point(field:agent.os.net.SockStatInfo.in_use)
    pub in_use: u64,
    // @@protoc_insertion_point(field:agent.os.net.SockStatInfo.orphan)
    pub orphan: u64,
    // @@protoc_insertion_point(field:agent.os.net.SockStatInfo.tw)
    pub tw: u64,
    // @@protoc_insertion_point(field:agent.os.net.SockStatInfo.alloc)
    pub alloc: u64,
    // @@protoc_insertion_point(field:agent.os.net.SockStatInfo.mem_kb)
    pub mem_kb: f64,
    // special fields
    // @@protoc_insertion_point(special_field:agent.os.net.SockStatInfo.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SockStatInfo {
    fn default() -> &'a SockStatInfo {
        <SockStatInfo as ::protobuf::Message>::default_instance()
    }
}

impl SockStatInfo {
    pub fn new() -> SockStatInfo {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "use_count",
            |m: &SockStatInfo| { &m.use_count },
            |m: &mut SockStatInfo| { &mut m.use_count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "in_use",
            |m: &SockStatInfo| { &m.in_use },
            |m: &mut SockStatInfo| { &mut m.in_use },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "orphan",
            |m: &SockStatInfo| { &m.orphan },
            |m: &mut SockStatInfo| { &mut m.orphan },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tw",
            |m: &SockStatInfo| { &m.tw },
            |m: &mut SockStatInfo| { &mut m.tw },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "alloc",
            |m: &SockStatInfo| { &m.alloc },
            |m: &mut SockStatInfo| { &mut m.alloc },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "mem_kb",
            |m: &SockStatInfo| { &m.mem_kb },
            |m: &mut SockStatInfo| { &mut m.mem_kb },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SockStatInfo>(
            "SockStatInfo",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SockStatInfo {
    const NAME: &'static str = "SockStatInfo";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.use_count = is.read_uint64()?;
                },
                16 => {
                    self.in_use = is.read_uint64()?;
                },
                24 => {
                    self.orphan = is.read_uint64()?;
                },
                32 => {
                    self.tw = is.read_uint64()?;
                },
                40 => {
                    self.alloc = is.read_uint64()?;
                },
                49 => {
                    self.mem_kb = is.read_double()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.use_count != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.use_count);
        }
        if self.in_use != 0 {
            my_size += ::protobuf::rt::uint64_size(2, self.in_use);
        }
        if self.orphan != 0 {
            my_size += ::protobuf::rt::uint64_size(3, self.orphan);
        }
        if self.tw != 0 {
            my_size += ::protobuf::rt::uint64_size(4, self.tw);
        }
        if self.alloc != 0 {
            my_size += ::protobuf::rt::uint64_size(5, self.alloc);
        }
        if self.mem_kb != 0. {
            my_size += 1 + 8;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.use_count != 0 {
            os.write_uint64(1, self.use_count)?;
        }
        if self.in_use != 0 {
            os.write_uint64(2, self.in_use)?;
        }
        if self.orphan != 0 {
            os.write_uint64(3, self.orphan)?;
        }
        if self.tw != 0 {
            os.write_uint64(4, self.tw)?;
        }
        if self.alloc != 0 {
            os.write_uint64(5, self.alloc)?;
        }
        if self.mem_kb != 0. {
            os.write_double(6, self.mem_kb)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SockStatInfo {
        SockStatInfo::new()
    }

    fn clear(&mut self) {
        self.use_count = 0;
        self.in_use = 0;
        self.orphan = 0;
        self.tw = 0;
        self.alloc = 0;
        self.mem_kb = 0.;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SockStatInfo {
        static instance: SockStatInfo = SockStatInfo {
            use_count: 0,
            in_use: 0,
            orphan: 0,
            tw: 0,
            alloc: 0,
            mem_kb: 0.,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SockStatInfo {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SockStatInfo").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SockStatInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SockStatInfo {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:agent.os.net.Tcp4Stat)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Tcp4Stat {
    // message fields
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stat.local_addr_hex)
    pub local_addr_hex: ::std::string::String,
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stat.remote_addr_hex)
    pub remote_addr_hex: ::std::string::String,
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stat.connection_state)
    pub connection_state: u32,
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stat.tx_queue)
    pub tx_queue: u64,
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stat.rx_queue)
    pub rx_queue: u64,
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stat.time_active)
    pub time_active: u32,
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stat.jiffies_timer_expires)
    pub jiffies_timer_expires: u64,
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stat.rto)
    pub rto: u64,
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stat.uid)
    pub uid: u32,
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stat.zero_window_probes)
    pub zero_window_probes: u32,
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stat.inode)
    pub inode: u64,
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stat.etc)
    pub etc: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:agent.os.net.Tcp4Stat.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Tcp4Stat {
    fn default() -> &'a Tcp4Stat {
        <Tcp4Stat as ::protobuf::Message>::default_instance()
    }
}

impl Tcp4Stat {
    pub fn new() -> Tcp4Stat {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(12);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "local_addr_hex",
            |m: &Tcp4Stat| { &m.local_addr_hex },
            |m: &mut Tcp4Stat| { &mut m.local_addr_hex },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "remote_addr_hex",
            |m: &Tcp4Stat| { &m.remote_addr_hex },
            |m: &mut Tcp4Stat| { &mut m.remote_addr_hex },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "connection_state",
            |m: &Tcp4Stat| { &m.connection_state },
            |m: &mut Tcp4Stat| { &mut m.connection_state },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tx_queue",
            |m: &Tcp4Stat| { &m.tx_queue },
            |m: &mut Tcp4Stat| { &mut m.tx_queue },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "rx_queue",
            |m: &Tcp4Stat| { &m.rx_queue },
            |m: &mut Tcp4Stat| { &mut m.rx_queue },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "time_active",
            |m: &Tcp4Stat| { &m.time_active },
            |m: &mut Tcp4Stat| { &mut m.time_active },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "jiffies_timer_expires",
            |m: &Tcp4Stat| { &m.jiffies_timer_expires },
            |m: &mut Tcp4Stat| { &mut m.jiffies_timer_expires },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "rto",
            |m: &Tcp4Stat| { &m.rto },
            |m: &mut Tcp4Stat| { &mut m.rto },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "uid",
            |m: &Tcp4Stat| { &m.uid },
            |m: &mut Tcp4Stat| { &mut m.uid },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "zero_window_probes",
            |m: &Tcp4Stat| { &m.zero_window_probes },
            |m: &mut Tcp4Stat| { &mut m.zero_window_probes },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "inode",
            |m: &Tcp4Stat| { &m.inode },
            |m: &mut Tcp4Stat| { &mut m.inode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "etc",
            |m: &Tcp4Stat| { &m.etc },
            |m: &mut Tcp4Stat| { &mut m.etc },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Tcp4Stat>(
            "Tcp4Stat",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Tcp4Stat {
    const NAME: &'static str = "Tcp4Stat";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.local_addr_hex = is.read_string()?;
                },
                18 => {
                    self.remote_addr_hex = is.read_string()?;
                },
                24 => {
                    self.connection_state = is.read_uint32()?;
                },
                32 => {
                    self.tx_queue = is.read_uint64()?;
                },
                40 => {
                    self.rx_queue = is.read_uint64()?;
                },
                48 => {
                    self.time_active = is.read_uint32()?;
                },
                56 => {
                    self.jiffies_timer_expires = is.read_uint64()?;
                },
                64 => {
                    self.rto = is.read_uint64()?;
                },
                72 => {
                    self.uid = is.read_uint32()?;
                },
                80 => {
                    self.zero_window_probes = is.read_uint32()?;
                },
                88 => {
                    self.inode = is.read_uint64()?;
                },
                98 => {
                    self.etc = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.local_addr_hex.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.local_addr_hex);
        }
        if !self.remote_addr_hex.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.remote_addr_hex);
        }
        if self.connection_state != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.connection_state);
        }
        if self.tx_queue != 0 {
            my_size += ::protobuf::rt::uint64_size(4, self.tx_queue);
        }
        if self.rx_queue != 0 {
            my_size += ::protobuf::rt::uint64_size(5, self.rx_queue);
        }
        if self.time_active != 0 {
            my_size += ::protobuf::rt::uint32_size(6, self.time_active);
        }
        if self.jiffies_timer_expires != 0 {
            my_size += ::protobuf::rt::uint64_size(7, self.jiffies_timer_expires);
        }
        if self.rto != 0 {
            my_size += ::protobuf::rt::uint64_size(8, self.rto);
        }
        if self.uid != 0 {
            my_size += ::protobuf::rt::uint32_size(9, self.uid);
        }
        if self.zero_window_probes != 0 {
            my_size += ::protobuf::rt::uint32_size(10, self.zero_window_probes);
        }
        if self.inode != 0 {
            my_size += ::protobuf::rt::uint64_size(11, self.inode);
        }
        if !self.etc.is_empty() {
            my_size += ::protobuf::rt::string_size(12, &self.etc);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.local_addr_hex.is_empty() {
            os.write_string(1, &self.local_addr_hex)?;
        }
        if !self.remote_addr_hex.is_empty() {
            os.write_string(2, &self.remote_addr_hex)?;
        }
        if self.connection_state != 0 {
            os.write_uint32(3, self.connection_state)?;
        }
        if self.tx_queue != 0 {
            os.write_uint64(4, self.tx_queue)?;
        }
        if self.rx_queue != 0 {
            os.write_uint64(5, self.rx_queue)?;
        }
        if self.time_active != 0 {
            os.write_uint32(6, self.time_active)?;
        }
        if self.jiffies_timer_expires != 0 {
            os.write_uint64(7, self.jiffies_timer_expires)?;
        }
        if self.rto != 0 {
            os.write_uint64(8, self.rto)?;
        }
        if self.uid != 0 {
            os.write_uint32(9, self.uid)?;
        }
        if self.zero_window_probes != 0 {
            os.write_uint32(10, self.zero_window_probes)?;
        }
        if self.inode != 0 {
            os.write_uint64(11, self.inode)?;
        }
        if !self.etc.is_empty() {
            os.write_string(12, &self.etc)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Tcp4Stat {
        Tcp4Stat::new()
    }

    fn clear(&mut self) {
        self.local_addr_hex.clear();
        self.remote_addr_hex.clear();
        self.connection_state = 0;
        self.tx_queue = 0;
        self.rx_queue = 0;
        self.time_active = 0;
        self.jiffies_timer_expires = 0;
        self.rto = 0;
        self.uid = 0;
        self.zero_window_probes = 0;
        self.inode = 0;
        self.etc.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Tcp4Stat {
        static instance: Tcp4Stat = Tcp4Stat {
            local_addr_hex: ::std::string::String::new(),
            remote_addr_hex: ::std::string::String::new(),
            connection_state: 0,
            tx_queue: 0,
            rx_queue: 0,
            time_active: 0,
            jiffies_timer_expires: 0,
            rto: 0,
            uid: 0,
            zero_window_probes: 0,
            inode: 0,
            etc: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Tcp4Stat {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Tcp4Stat").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Tcp4Stat {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Tcp4Stat {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:agent.os.net.Tcp4Stats)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Tcp4Stats {
    // message fields
    // @@protoc_insertion_point(field:agent.os.net.Tcp4Stats.stats)
    pub stats: ::std::vec::Vec<Tcp4Stat>,
    // special fields
    // @@protoc_insertion_point(special_field:agent.os.net.Tcp4Stats.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Tcp4Stats {
    fn default() -> &'a Tcp4Stats {
        <Tcp4Stats as ::protobuf::Message>::default_instance()
    }
}

impl Tcp4Stats {
    pub fn new() -> Tcp4Stats {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "stats",
            |m: &Tcp4Stats| { &m.stats },
            |m: &mut Tcp4Stats| { &mut m.stats },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Tcp4Stats>(
            "Tcp4Stats",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Tcp4Stats {
    const NAME: &'static str = "Tcp4Stats";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.stats.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.stats {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.stats {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Tcp4Stats {
        Tcp4Stats::new()
    }

    fn clear(&mut self) {
        self.stats.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Tcp4Stats {
        static instance: Tcp4Stats = Tcp4Stats {
            stats: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Tcp4Stats {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Tcp4Stats").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Tcp4Stats {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Tcp4Stats {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\tnet.proto\x12\x0cagent.os.net\"o\n\x07ArpInfo\x12\x1d\n\nip_address\
    \x18\x01\x20\x01(\tR\tipAddress\x12\x17\n\x07hw_type\x18\x02\x20\x01(\rR\
    \x06hwType\x12\x14\n\x05flags\x18\x03\x20\x01(\tR\x05flags\x12\x16\n\x06\
    device\x18\x04\x20\x01(\tR\x06device\"7\n\x08ArpInfos\x12+\n\x05infos\
    \x18\x01\x20\x03(\x0b2\x15.agent.os.net.ArpInfoR\x05infos\"\xb4\x03\n\nN\
    etDevInfo\x12\x1c\n\tinterface\x18\x01\x20\x01(\tR\tinterface\x12\x19\n\
    \x08rx_bytes\x18\x02\x20\x01(\x04R\x07rxBytes\x12\x1d\n\nrx_packets\x18\
    \x03\x20\x01(\x04R\trxPackets\x12\x17\n\x07rx_errs\x18\x04\x20\x01(\x04R\
    \x06rxErrs\x12\x17\n\x07rx_drop\x18\x05\x20\x01(\x04R\x06rxDrop\x12\x17\
    \n\x07rx_fifo\x18\x06\x20\x01(\x04R\x06rxFifo\x12\x19\n\x08rx_frame\x18\
    \x07\x20\x01(\x04R\x07rxFrame\x12#\n\rrx_compressed\x18\x08\x20\x01(\x04\
    R\x0crxCompressed\x12\x19\n\x08tx_bytes\x18\t\x20\x01(\x04R\x07txBytes\
    \x12\x1d\n\ntx_packets\x18\n\x20\x01(\x04R\ttxPackets\x12\x17\n\x07tx_er\
    rs\x18\x0b\x20\x01(\x04R\x06txErrs\x12\x17\n\x07tx_drop\x18\x0c\x20\x01(\
    \x04R\x06txDrop\x12\x17\n\x07tx_fifo\x18\r\x20\x01(\x04R\x06txFifo\x12\
    \x19\n\x08tx_frame\x18\x0e\x20\x01(\x04R\x07txFrame\x12#\n\rtx_compresse\
    d\x18\x0f\x20\x01(\x04R\x0ctxCompressed\"=\n\x0bNetDevInfos\x12.\n\x05in\
    fos\x18\x01\x20\x03(\x0b2\x18.agent.os.net.NetDevInfoR\x05infos\"\x97\
    \x01\n\x0cSockStatInfo\x12\x1b\n\tuse_count\x18\x01\x20\x01(\x04R\x08use\
    Count\x12\x15\n\x06in_use\x18\x02\x20\x01(\x04R\x05inUse\x12\x16\n\x06or\
    phan\x18\x03\x20\x01(\x04R\x06orphan\x12\x0e\n\x02tw\x18\x04\x20\x01(\
    \x04R\x02tw\x12\x14\n\x05alloc\x18\x05\x20\x01(\x04R\x05alloc\x12\x15\n\
    \x06mem_kb\x18\x06\x20\x01(\x01R\x05memKb\"\x88\x03\n\x08Tcp4Stat\x12$\n\
    \x0elocal_addr_hex\x18\x01\x20\x01(\tR\x0clocalAddrHex\x12&\n\x0fremote_\
    addr_hex\x18\x02\x20\x01(\tR\rremoteAddrHex\x12)\n\x10connection_state\
    \x18\x03\x20\x01(\rR\x0fconnectionState\x12\x19\n\x08tx_queue\x18\x04\
    \x20\x01(\x04R\x07txQueue\x12\x19\n\x08rx_queue\x18\x05\x20\x01(\x04R\
    \x07rxQueue\x12\x1f\n\x0btime_active\x18\x06\x20\x01(\rR\ntimeActive\x12\
    2\n\x15jiffies_timer_expires\x18\x07\x20\x01(\x04R\x13jiffiesTimerExpire\
    s\x12\x10\n\x03rto\x18\x08\x20\x01(\x04R\x03rto\x12\x10\n\x03uid\x18\t\
    \x20\x01(\rR\x03uid\x12,\n\x12zero_window_probes\x18\n\x20\x01(\rR\x10ze\
    roWindowProbes\x12\x14\n\x05inode\x18\x0b\x20\x01(\x04R\x05inode\x12\x10\
    \n\x03etc\x18\x0c\x20\x01(\tR\x03etc\"9\n\tTcp4Stats\x12,\n\x05stats\x18\
    \x01\x20\x03(\x0b2\x16.agent.os.net.Tcp4StatR\x05statsB'\xaa\x02$InfoGat\
    herHub.HubProtos.Agent.Os.Netb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(7);
            messages.push(ArpInfo::generated_message_descriptor_data());
            messages.push(ArpInfos::generated_message_descriptor_data());
            messages.push(NetDevInfo::generated_message_descriptor_data());
            messages.push(NetDevInfos::generated_message_descriptor_data());
            messages.push(SockStatInfo::generated_message_descriptor_data());
            messages.push(Tcp4Stat::generated_message_descriptor_data());
            messages.push(Tcp4Stats::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
